[package]
name = "matoran-dictionary"
version = "0.1.0"
authors = ["Mike Harding <redoxeon@mharding.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
nom = "5.1.1"
